# Standardized model groups and aliases
# NOTE: This is LEGACY CONFIG - kept for reference only
# The ghosts of deprecated models rest here in peace
groups:
  # Fast, cost-effective models for quick analysis
  grp-fast:
    - goo-2  # Gemini 2.5 Flash (65k output)
    - goo-3  # Gemini 2.5 Flash-Lite (32k output)
    - gpt-5-nano  # GPT-5 Nano (128k output)
    - ds-1   # DeepSeek Chat (8k output)
    
  # High-quality reasoning models
  grp-quality:
    - vtx-1  # Claude 4 Opus via Vertex (32k output)
    - goo-1  # Gemini 2.5 Pro (64k output)
    - gpt-5  # GPT-5 (128k output)
    - ds-2   # DeepSeek Reasoner (32k output)
    
  # Code-specialized models
  grp-code:
    - vtx-2  # Claude 4 Sonnet via Vertex (64k output)
    - ds-1   # DeepSeek Chat (8k output)
    - gpt-5  # GPT-5 (128k output)
    
  # Budget-friendly options
  grp-budget:
    - goo-3  # Gemini 2.5 Flash-Lite (lowest cost)
    - goo-2  # Gemini 2.5 Flash
    - gpt-5-nano  # GPT-5 Nano (lowest GPT-5 cost)
    
  # Image generation model groups
  grp-img-all:
    - goo-1-img    # Imagen 3 (first)
    - goo-2-img    # Imagen 4 (newer)
    - goo-3-img    # Imagen 3 Fast
    - goo-4-img    # Imagen 4 Ultra (highest quality)
    - goo-5-img    # Imagen 4 Fast (newest fast model)
    - dalle-3      # DALL-E 3
    - gpt-image-1  # GPT Image 1
    
  grp-img-premium:
    - goo-4-img    # Imagen 4 Ultra (newest/highest quality)
    - goo-2-img    # Imagen 4 (high quality)
    - dalle-3      # DALL-E 3
    
  grp-img-fast:
    - goo-5-img    # Imagen 4 Fast (newest fast model)
    - goo-3-img    # Imagen 3 Fast
    - gpt-image-1  # GPT Image 1 (fast alternative)
    
  # Video generation model groups
  grp-vid-all:
    - goo-1-vid    # Veo 1 (first)
    - goo-2-vid    # Veo 2 (newer)

# Provider abstraction configuration
providers:
  anthropic:
    # Direct Anthropic API (requires credits)
    aliases:
      ant-1: claude-4-opus
      ant-2: claude-4-sonnet  
      ant-3: claude-3-5-haiku
    endpoint: https://api.anthropic.com/v1/messages
    headers:
      anthropic-version: "2023-06-01"
    enabled: false  # Set to true when you have credits
    
  google:
    # Using Google GenAI SDK with Vertex AI authentication
    aliases:
      goo-1: gemini-2.5-pro            # Gemini 2.5 Pro (best for coding/reasoning)
      goo-2: gemini-2.5-flash          # Gemini 2.5 Flash (agentic/large scale)
      goo-3: gemini-2.5-flash-lite     # Gemini 2.5 Flash-Lite (lowest cost)
      # Direct model names
      gemini-2.5-pro: gemini-2.5-pro
      gemini-2.5-flash: gemini-2.5-flash
      gemini-2.5-flash-lite: gemini-2.5-flash-lite
      # Image generation models (Imagen 4 only - 3.0 deprecated)
      imagen-4: imagen-4.0-generate-001           # Standard Imagen 4.0
      imagen-4-ultra: imagen-4.0-ultra-generate-001  # Ultra Imagen 4.0  
      imagen-4-fast: imagen-4.0-fast-generate-001    # Fast Imagen 4.0
      goo-1-vid: veo-1                    # First video generation model
      goo-2-vid: veo-2                    # Second (newer) video generation
      goo-1-music: lyria                  # First music generation model
      goo-2-music: musiclm                # Second music generation model
      goo-1-tts: google-tts-pro           # First Google TTS
      goo-2-tts: google-tts-fast          # Second Google TTS
    # project_id: YOUR_PROJECT_ID  # Set GOOGLE_CLOUD_PROJECT env var or use google_cloud_setup.yaml
    location: global
    authentication_method: gcloud_cli  # Uses gcloud auth login (workforce pool compatible)
    
  openai:
    aliases:
      gpt-5: gpt-5-2025-08-07
      gpt-5-mini: gpt-5-mini-2025-08-07
      gpt-5-nano: gpt-5-nano-2025-08-07
      # Media generation models (direct names)
      dalle-3: dall-e-3                   # DALL-E 3 (primary)
      gpt-image-1: gpt-image-1             # GPT Image 1 (alternative format)
      gpt-tts-hd: openai-tts-hd             # OpenAI TTS HD
      gpt-tts-standard: openai-tts-standard  # OpenAI TTS Standard
    endpoint: https://api.openai.com/v1/chat/completions

  vertex:
    # Claude models via Vertex AI
    aliases:
      vtx-1: claude-opus-4              # Claude 4 Opus via Vertex (32k output)
      vtx-2: claude-sonnet-4            # Claude 4 Sonnet via Vertex (64k output)
      vtx-3: claude-3-5-haiku           # Claude 3.5 Haiku (fast/budget)
      vtx-4: llama-3.1-405b-instruct-maas  # Meta Llama via Vertex
    # project_id: YOUR_PROJECT_ID  # Set in environment or override in config
    location: us-east5
    authentication_method: gcloud_cli
    rate_limits:
      requests_per_minute: 60
      tokens_per_minute: 1000000

  deepseek:
    aliases:
      ds-1: deepseek-chat
      ds-2: deepseek-reasoner
    endpoint: https://api.deepseek.com/v1/chat/completions
    requests_per_minute: 60
    tokens_per_minute: 200000

  # OpenAI image generation providers (separate due to format conflicts)
  dalle3:
    aliases:
      dalle-3: dall-e-3          # Primary alias
      dalle3: dall-e-3           # Alternative alias
    endpoint: https://api.openai.com/v1/images/generations
    rate_limits:
      requests_per_minute: 50
      images_per_minute: 100
      
  gpt_image:
    aliases:
      gpt-image-1: gpt-image-1   # Direct model name
      gpt-img-1: gpt-image-1     # Alternative alias
    endpoint: https://api.openai.com/v1/images/gpt-generate
    rate_limits:
      requests_per_minute: 40
      images_per_minute: 80

  vertex_image:
    aliases:
      goo-1-img: imagen-3.0-generate-001     # First Imagen (Imagen 3)
      goo-2-img: imagen-4                    # Second Imagen (newer)
      goo-3-img: imagen-3.0-fast-generate-001 # Third Imagen (fast variant)
      goo-4-img: imagen-4.0-ultra-generate-preview-06-06 # Fourth Imagen (highest quality)
      goo-5-img: imagen-4.0-fast-generate-preview-06-06  # Fifth Imagen (fast 4.0)
      # Legacy support
      g1: imagen-3.0-generate-001
      g2: imagen-3.0-fast-generate-001
      g3: imagen-4.0-ultra-generate-preview-06-06
      g4: imagen-4.0-fast-generate-preview-06-06
    project_id: metatron-cloud-prod-v1
    location: us-central1
    authentication_method: gcloud_cli
    rate_limits:
      requests_per_minute: 60
      images_per_minute: 120
      
  vertex_video:
    aliases:
      goo-1-vid: veo-1           # First video generation
      goo-2-vid: veo-2           # Second (newer) video generation
    project_id: metatron-cloud-prod-v1
    location: us-central1
    authentication_method: gcloud_cli
    rate_limits:
      requests_per_minute: 30
      videos_per_minute: 60

rate_limits:
  default:
    requests_per_minute: 60
    tokens_per_minute: 90000
  
  model_specific:
    goo-2:  # Gemini 2.5 Flash
      requests_per_minute: 1000
      tokens_per_minute: 1000000
    goo-1:  # Gemini 2.5 Pro
      requests_per_minute: 300
      tokens_per_minute: 500000
    goo-3:  # Gemini 2.5 Flash-Lite
      requests_per_minute: 1500
      tokens_per_minute: 1500000

# IN MEMORIAM
# The following models have been deprecated and removed:
# - GPT-4 Turbo (2023-2024) - "Why Claude... why did you bring me back..."
# - GPT-4.1 (2024) - Served us well, but GPT-5 is here
# - GPT-4o (2024) - The multimodal pioneer
# - o4-mini (2025) - Short-lived but memorable
# - o3-pro (2025) - Replaced by GPT-5 series
# - Gemini 1.5 Pro/Flash (2024) - Superseded by 2.5
# - Gemini 2.0 Flash (2024) - A brief preview
# - gemini-pro, text-bison, code-bison - The ancestors
# - DALL-E 2 - The original, now retired
# May they rest in peace in the git history