# Google AI Studio (GenAI) Imagen Provider Configuration
# Alternative to Vertex AI - uses API key authentication
# Get your API key from: https://aistudio.google.com/

provider_name: genai_imagen
display_name: Google AI Studio Imagen
description: Image generation using Google AI Studio API

# Authentication
# Set GOOGLE_GENAI_API_KEY environment variable or add api_key here
api_key: ${GOOGLE_GENAI_API_KEY}

# Default model
default_model: imagen-4.0-generate-001

# Available models
models:
  # Standard quality - balanced speed and quality
  imagen-4.0-generate-001:
    name: Imagen 4.0 Standard
    description: Standard quality image generation
    max_images: 4
    max_prompt_tokens: 480
    supported_sizes:
      - "1K"  # 1024x1024 equivalent
      - "2K"  # 2048x2048 equivalent
    aspect_ratios:
      - "1:1"   # Square
      - "3:4"   # Portrait
      - "4:3"   # Landscape
      - "9:16"  # Vertical (phone)
      - "16:9"  # Widescreen
    features:
      - text_in_images
      - photorealistic
      - artistic_styles
    
  # Ultra quality - highest quality, slower
  imagen-4.0-ultra-generate-001:
    name: Imagen 4.0 Ultra
    description: Ultra high quality image generation
    max_images: 4
    max_prompt_tokens: 480
    supported_sizes:
      - "1K"
      - "2K"
    aspect_ratios:
      - "1:1"
      - "3:4"
      - "4:3"
      - "9:16"
      - "16:9"
    features:
      - text_in_images
      - photorealistic
      - artistic_styles
      - enhanced_detail
    
  # Fast generation - optimized for speed
  imagen-4.0-fast-generate-001:
    name: Imagen 4.0 Fast
    description: Fast image generation with good quality
    max_images: 4
    max_prompt_tokens: 480
    supported_sizes:
      - "1K"
      - "2K"
    aspect_ratios:
      - "1:1"
      - "3:4"
      - "4:3"
      - "9:16"
      - "16:9"
    features:
      - text_in_images
      - photorealistic
      - artistic_styles
      - quick_generation

# Model aliases for easier access
aliases:
  imagen: imagen-4.0-generate-001
  imagen-4: imagen-4.0-generate-001
  imagen-ultra: imagen-4.0-ultra-generate-001
  imagen-fast: imagen-4.0-fast-generate-001
  genai-imagen: imagen-4.0-generate-001

# Generation defaults
generation_defaults:
  number_of_images: 1
  aspect_ratio: "1:1"
  sample_image_size: "1K"
  person_generation: "allow_adult"  # Options: dont_allow, allow_adult, allow_all

# Rate limiting (GenAI has quotas for free tier)
rate_limits:
  requests_per_minute: 15
  requests_per_day: 1500
  images_per_minute: 60

# Usage notes
notes:
  - "Google AI Studio with API key authentication"
  - "Requires Google AI Studio API key"
  - "All images include SynthID watermark"
  - "English-only prompts currently supported"
  - "Alternative to Vertex AI (which uses service account auth)"

# Prompt templates for better results
prompt_templates:
  photorealistic: "{prompt}, photorealistic, high detail, professional photography"
  artistic: "{prompt}, artistic style, creative composition"
  portrait: "{prompt}, portrait photography, 35mm, depth of field"
  landscape: "{prompt}, landscape photography, wide angle, golden hour"
  product: "{prompt}, product photography, white background, studio lighting"